import { c as create_ssr_component, b as add_attribute } from "../../chunks/ssr.js";
const welcome_fallback = "/_app/immutable/assets/suncharge.BSaVDO6e.jpg";
const css = {
  code: "section.svelte-5ru9qe.svelte-5ru9qe{display:flex;flex-direction:column;justify-content:center;align-items:center;flex:0.6}h1.svelte-5ru9qe.svelte-5ru9qe{width:100%}.welcome.svelte-5ru9qe.svelte-5ru9qe{display:block;position:relative;width:100%;height:0;padding:0 0 calc(100% * 500 / 2048) 0}.welcome.svelte-5ru9qe img.svelte-5ru9qe{position:absolute;width:100%;height:150px;top:0;display:block}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script>\\r\\n\\timport welcome from \\"$lib/images/suncharge.jpg\\";\\r\\n\\timport welcome_fallback from \\"$lib/images/suncharge.jpg\\";\\r\\n<\/script>\\r\\n\\r\\n<svelte:head>\\r\\n\\t<title>Main</title>\\r\\n\\t<meta name=\\"description\\" content=\\"dvproject\\" />\\r\\n</svelte:head>\\r\\n\\r\\n<section>\\r\\n\\t<h1>\\r\\n\\t\\t<span class=\\"welcome\\">\\r\\n\\t\\t\\t<picture>\\r\\n\\t\\t\\t\\t<source srcset={welcome} type=\\"image/jpg\\" />\\r\\n\\t\\t\\t\\t<img src={welcome_fallback} alt=\\"Welcome\\" />\\r\\n\\t\\t\\t</picture>\\r\\n\\t\\t</span>\\r\\n\\t\\tWelcome to Your New Supply Chain Dashboard\\r\\n\\t</h1>\\r\\n\\r\\n\\t<main />\\r\\n</section>\\r\\n\\r\\n<style>\\r\\n\\tsection {\\r\\n\\t\\tdisplay: flex;\\r\\n\\t\\tflex-direction: column;\\r\\n\\t\\tjustify-content: center;\\r\\n\\t\\talign-items: center;\\r\\n\\t\\tflex: 0.6;\\r\\n\\t}\\r\\n\\r\\n\\th1 {\\r\\n\\t\\twidth: 100%;\\r\\n\\t}\\r\\n\\r\\n\\t.welcome {\\r\\n\\t\\tdisplay: block;\\r\\n\\t\\tposition: relative;\\r\\n\\t\\twidth: 100%;\\r\\n\\t\\theight: 0;\\r\\n\\t\\tpadding: 0 0 calc(100% * 500 / 2048) 0;\\r\\n\\t}\\r\\n\\r\\n\\t.welcome img {\\r\\n\\t\\tposition: absolute;\\r\\n\\t\\twidth: 100%;\\r\\n\\t\\theight: 150px;\\r\\n\\t\\ttop: 0;\\r\\n\\t\\tdisplay: block;\\r\\n\\t}\\r\\n</style>\\r\\n"],"names":[],"mappings":"AAyBC,mCAAQ,CACP,OAAO,CAAE,IAAI,CACb,cAAc,CAAE,MAAM,CACtB,eAAe,CAAE,MAAM,CACvB,WAAW,CAAE,MAAM,CACnB,IAAI,CAAE,GACP,CAEA,8BAAG,CACF,KAAK,CAAE,IACR,CAEA,oCAAS,CACR,OAAO,CAAE,KAAK,CACd,QAAQ,CAAE,QAAQ,CAClB,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,CAAC,CACT,OAAO,CAAE,CAAC,CAAC,CAAC,CAAC,KAAK,IAAI,CAAC,CAAC,CAAC,GAAG,CAAC,CAAC,CAAC,IAAI,CAAC,CAAC,CACtC,CAEA,sBAAQ,CAAC,iBAAI,CACZ,QAAQ,CAAE,QAAQ,CAClB,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,KAAK,CACb,GAAG,CAAE,CAAC,CACN,OAAO,CAAE,KACV"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-13nli4f_START -->${$$result.title = `<title>Main</title>`, ""}<meta name="description" content="dvproject"><!-- HEAD_svelte-13nli4f_END -->`, ""} <section class="svelte-5ru9qe" data-svelte-h="svelte-1r15sci"><h1 class="svelte-5ru9qe"><span class="welcome svelte-5ru9qe"><picture><source${add_attribute("srcset", welcome_fallback, 0)} type="image/jpg"> <img${add_attribute("src", welcome_fallback, 0)} alt="Welcome" class="svelte-5ru9qe"></picture></span>
		Welcome to Your New Supply Chain Dashboard</h1> <main></main> </section>`;
});
export {
  Page as default
};
